#!/bin/bash

if [[ ${1} = "-h" ]] || [[ ${1} = "-?" ]] || [[ ${1} = "?" ]] ; then
  echo "Usage: $(basename ${0}) [<look-back>]"
  echo ""
  echo "Look-back is a number that indictaes how many days in the past"
  echo "the trades took place"
  exit 0
fi

# Function to get first index of an item in an array
getIndex() {
  local toFind=${1}
  shift
  local i=0;
  for v in ${@}
  do
    if [[ $v == $toFind ]]; then
      echo ${i};
      return;
    fi;
  i=$((i + 1));
  done;
  echo -1;
}

# Calculate date for stock trade
currDate=$(date +%Y%m%d)
regexCheckIfNumber='^[0-9]+$'
if [[ ${1} != "" ]] ; then
  if ! [[ ${1} =~ ${regexCheckIfNumber} ]]  ; then
     echo "Look-back input is not a number" >&2;
     exit 1
  fi
fi

if [[ ${1} = "" ]]; then
  lookBack=0
else
  lookBack=${1}
fi

d=$(date -d "${currDate} -${lookBack} day" +%Y.%m.%d);

echo $d

# Project working directory and files
fileroot="$( cd "$(dirname "$0")" || exit >/dev/null 2>&1 ; pwd -P )"
autotrading_file="${fileroot}/data/user_data/autotrading"
traded_stock_file="${fileroot}/data/user_data/trades"

# Prepare arrays
rateFiles=$(find "${fileroot}"/data/rates/*)
stocksToTrade=()
tradeTypesToTrade=()
amountsToTrade=()

# Get autotrades
if [[ -f ${autotrading_file} ]]; then
  while IFS="," read -r stk trdtp amt
  do
    stocksToTrade+=(${stk})
    tradeTypesToTrade+=(${trdtp})
    amountsToTrade+=(${amt})
  done < "${autotrading_file}"
else
  echo "${autotrading_file} does not exist" >&2
  exit 1
fi

# Get rates for date being traded
stockNames=()
stockRates=()
for rateFile in ${rateFiles[@]}
do
  tmpRate=0
  baseNameRateFile=$(basename ${rateFile})
  stockNames+=(${baseNameRateFile})
  if [[ -f ${rateFile} ]]; then
    while IFS="," read -r dte rte
    do
      if [[ ${dte} == ${d} ]] ; then
        tmpRate=${rte}
      fi
    done < "${rateFile}"
    if [[ ${tmpRate} = 0 ]] ; then
      echo "No rate found for stock ${stockNames[-1]} for date ${d}" >&2
      exit 1
    else
      stockRates+=(${tmpRate})
    fi
  else
    echo "${rateFile} does not exist" >&2
  fi
done

# Check if all stocks attempted to be bought or sold are being tracked
i=0
for stockToTrade in ${stocksToTrade[@]}
do
  index=$(getIndex ${stockToTrade} ${stockNames[@]})
  if [ ${index} -eq "-1" ] ; then
    echo "Rate data for stock ${stockToTrade} not found" >&2
    exit 1
  else
    if [ ${tradeTypesToTrade[${i}]} = "u" ]; then
      # Unit trade
      lineToAdd="${d},${stockToTrade},${amountsToTrade[${i}]}"
    fi
    if [ ${tradeTypesToTrade[${i}]} = "p" ]; then
      # Price trade
      indexOfStockPrice=$(getIndex ${stockToTrade} ${stockNames})
      stockPriceOnDate=${stockRates[${indexOfStockPrice}]}
      unitsToTrade=$(awk '{print $1/$2}' <<< "${amountsToTrade[${i}]} ${stockPriceOnDate}" )
      lineToAdd="${d},${stockToTrade},${unitsToTrade}"
    fi
  fi
  # Write trade to console and file
  echo ${lineToAdd}
  echo ${lineToAdd} >> "${traded_stock_file}"
  i=$((i+1))
done
